GET http://localhost:5000/all-order
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ2FoYW5naXIiLCJlbWFpbCI6Im1pc2hvZ2FoYW5naXJAZ21haWwuY29tIiwicGhvbmUiOiIwMTMwNjk5MDY3NiIsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjQxMzcwMjMzfQ.tumyMC1NE0VWX2K_GvuFPCrYNF_bNOFcRItfxoVtYv0